### ISSUE TITLE
Unordered Lists not rendering correctly

### ISSUE THREAD

**Issue by Sythelux** [mister-mcgee/obsidian-fill-in-the-blank#2]
Hello, first thank you for the extension. I love to use it at school as teacher.

I got the issue, that when I want to put blanks behind a bullet point in an unordered list the whole alignment is borked.

this is the input:
![grafik](https://github.com/mister-mcgee/obsidian-fill-in-the-blank/assets/601797/d1efa0ae-28df-47f4-855d-e657dec8ce53)

this is what it renders out:
![grafik](https://github.com/mister-mcgee/obsidian-fill-in-the-blank/assets/601797/e75db065-42fc-4250-b2f5-2814caeacd15)

This is closer to what I expected it to do:
![grafik](https://github.com/mister-mcgee/obsidian-fill-in-the-blank/assets/601797/d7329782-fe01-409f-9338-01201fcf59ae)
(was doing it manually to emphasize the issue.)

**Comment by mister-mcgee** [comment]
Hello, thank you for reaching out! Would you mind letting me know what version of the plugin you are using by going to Settings -> Community Plugins and finding the version number under the plugin name?

I can't seem to replicate this behavior with the current version of the plugin (1.0.4)

**Comment by Sythelux** [comment]
Ah it... works with 1.0.4 now.
I actually updated yesterday from 1.0.3 to 1.0.4 but I must've forgotten to restart the App.

Thanks for the help anyway and the quick response.

**Comment by mister-mcgee** [comment]
No problem! I'm glad I could help. If you ever have any other issues or requests, let me know!
